create extension if not exists pgcrypto;

create table if not exists public.cricheroes_teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  logo_url text,
  source_url text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cricheroes_players (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.cricheroes_teams(id) on delete cascade,
  name text not null,
  subtitle text,
  profile_url text,
  profile_pic_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(team_id, profile_url)
);

create table if not exists public.cricheroes_matches (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.cricheroes_teams(id) on delete cascade,
  tournament text,
  info text,
  match_date date,
  scores jsonb not null default '[]'::jsonb,
  result text,
  source_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(team_id, source_url)
);

create table if not exists public.cricheroes_sync_runs (
  id bigint generated by default as identity primary key,
  team_id uuid not null references public.cricheroes_teams(id) on delete cascade,
  completed_at timestamptz not null default now(),
  match_count integer not null default 0,
  player_count integer not null default 0
);

alter table public.cricheroes_teams enable row level security;
alter table public.cricheroes_players enable row level security;
alter table public.cricheroes_matches enable row level security;
alter table public.cricheroes_sync_runs enable row level security;

create policy "public can read cricheroes teams" on public.cricheroes_teams for select using (true);
create policy "public can read cricheroes players" on public.cricheroes_players for select using (true);
create policy "public can read cricheroes matches" on public.cricheroes_matches for select using (true);
